"""
Massive Topics Database for MindRank YouTube Channel
500+ psychology, rankings, and facts topics organized by category
Auto-rotates and never repeats until all topics are used
"""

# ─── DARK PSYCHOLOGY ─────────────────────────────────────────────
DARK_PSYCHOLOGY = [
    "The dark psychology trick that works every time",
    "The manipulation tactic narcissists use on everyone",
    "How to tell if someone is lying to you instantly",
    "The psychological trap most people fall into daily",
    "Why toxic people always seem so charming at first",
    "The dark secret behind every cult leader's charisma",
    "How sociopaths manipulate you without you knowing",
    "The psychological weapon used in every argument",
    "Why you always forgive people who don't deserve it",
    "The mind control technique used by salespeople",
    "How to spot a manipulator in under 30 seconds",
    "The dark reason why some people enjoy hurting others",
    "Why narcissists always play the victim",
    "The psychological trick to make anyone like you",
    "How to emotionally detach from toxic people",
    "The dark psychology behind gaslighting",
    "Why manipulators target empaths specifically",
    "The psychological profile of a serial liar",
    "How to protect yourself from psychological manipulation",
    "The dark art of persuasion nobody talks about",
    "Why people with dark triad personalities are so dangerous",
    "The psychological reason you keep going back to toxic exes",
    "How to spot hidden aggression in someone's behavior",
    "The dark truth about people who never apologize",
    "Why some people enjoy watching others suffer",
    "The psychological trap of the sunk cost fallacy",
    "How to disarm a narcissist in one sentence",
    "The dark psychology behind love bombing",
    "Why manipulators always seem so confident",
    "The psychological weapon hidden in every compliment",
]

# ─── INTELLIGENCE & BRAIN ────────────────────────────────────────
INTELLIGENCE = [
    "Top 5 signs you are a genius but don't know it",
    "7 signs you are smarter than you think",
    "Why high IQ people are actually lonelier",
    "The surprising link between intelligence and mental illness",
    "Why smart people make the worst decisions",
    "The psychological profile of a genius",
    "Why intelligent people struggle with relationships",
    "The dark side of being highly intelligent",
    "Why smart people are more likely to overthink",
    "The surprising reason intelligent people curse more",
    "Why geniuses often appear crazy to normal people",
    "The psychological reason smart people doubt themselves",
    "Why intelligent people are harder to convince",
    "The surprising connection between humor and intelligence",
    "Why smart people prefer to be alone",
    "The psychological cost of high intelligence",
    "Why intelligent people make terrible employees",
    "The dark secret behind every genius's mind",
    "Why smart people are more prone to depression",
    "The surprising trait all geniuses share",
    "Why intelligent people can't stop thinking",
    "The psychological reason smart people procrastinate",
    "Why geniuses always look tired",
    "The hidden downside of above average intelligence",
    "Why smart people are more likely to cheat",
    "The psychological warfare inside a genius's brain",
    "Why intelligent people struggle with small talk",
    "The surprising link between intelligence and insomnia",
    "Why smart people are harder to brainwash",
    "The dark truth about people with photographic memory",
]

# ─── BODY LANGUAGE ───────────────────────────────────────────────
BODY_LANGUAGE = [
    "5 body language secrets that reveal someone's intentions",
    "How to read someone's personality by their habits",
    "The body language sign that means someone is attracted to you",
    "Why people touch their face when they're lying",
    "The subconscious body language of a confident person",
    "How to tell if someone is uncomfortable around you",
    "The eye contact trick that reveals someone's true feelings",
    "Why people cross their arms and what it really means",
    "The body language of someone who is hiding something",
    "How to spot a fake smile instantly",
    "The foot direction trick to read someone's interest",
    "Why people mirror your body language",
    "The hand gesture that signals dominance",
    "How to tell if someone is attracted to you from across the room",
    "The body language of someone who is intimidated",
    "Why people lean away when they don't like you",
    "The subtle sign someone is losing interest in you",
    "How to read micro expressions in real time",
    "The body language of a natural leader",
    "Why people fidget when they're nervous",
    "The arm position that reveals someone's confidence level",
    "How to spot a sociopath by their body language",
    "The head tilt trick to make anyone trust you",
    "Why people look left when they're lying",
    "The body language of someone who is attracted to you",
    "How to tell if someone is bored by your conversation",
    "The hand gesture that signals honesty",
    "Why people touch their neck when they're stressed",
    "The body language of a person who is hiding pain",
    "How to read someone's true intentions from their posture",
]

# ─── RELATIONSHIPS ───────────────────────────────────────────────
RELATIONSHIPS = [
    "The friendship formula that psychology discovered",
    "Why breakups physically hurt",
    "The psychology of attraction nobody talks about",
    "5 signs someone is secretly jealous of you",
    "Why we sabotage our own success",
    "The psychology behind why songs get stuck in your head",
    "The truth about introverts nobody believes",
    "Why your brain lies to you about danger",
    "The psychological reason you miss someone who hurt you",
    "Why people ghost you and what it really means",
    "The psychology behind why we love music so much",
    "The surprising reason you can't forget your ex",
    "Why some people can't be alone",
    "The psychological reason you attract toxic people",
    "Why people stay in bad relationships",
    "The psychology behind why we dream about exes",
    "Why love hurts more than physical pain",
    "The psychological reason you fear abandonment",
    "Why some people are naturally flirty",
    "The psychology behind why we cheat",
    "Why people lie in relationships",
    "The psychological reason you feel lonely in a crowd",
    "Why some people are addicted to drama",
    "The psychology behind why we fall in love",
    "Why people push away the ones they love most",
    "The psychological reason you can't move on",
    "Why some people are emotionally unavailable",
    "The psychology behind why we get jealous",
    "Why people cheat even when they're happy",
    "The psychological reason you fear intimacy",
]

# ─── COGNITIVE BIASES ────────────────────────────────────────────
COGNITIVE_BIASES = [
    "5 cognitive biases that control your decisions",
    "The psychological reason you believe things that aren't true",
    "Why your brain always takes the easy way out",
    "The cognitive bias that makes you think you're special",
    "Why you always think you're right even when you're wrong",
    "The psychological reason you follow the crowd",
    "Why your memory is lying to you right now",
    "The cognitive bias that ruins every relationship",
    "Why you always procrastinate on important tasks",
    "The psychological reason you fear change",
    "Why your brain filters out most of reality",
    "The cognitive bias that makes you see patterns everywhere",
    "Why you always assume the worst about people",
    "The psychological reason you can't stop worrying",
    "Why your brain prefers familiar pain over unknown pleasure",
    "The cognitive bias that makes you overspend",
    "Why you always think tomorrow will be better",
    "The psychological reason you can't stick to habits",
    "Why your brain makes you eat junk food",
    "The cognitive bias that ruins your judgment",
    "Why you always look for evidence that confirms your beliefs",
    "The psychological reason you fear public speaking",
    "Why your brain can't distinguish real from imagined danger",
    "The cognitive bias that makes you trust attractive people",
    "Why you always think you're better than average",
    "The psychological reason you feel guilty for no reason",
    "Why your brain makes you procrastinate",
    "The cognitive bias that makes you impulsive",
    "Why you always think you have more time than you do",
    "The psychological reason you can't concentrate",
]

# ─── SUCCESS & MOTIVATION ────────────────────────────────────────
SUCCESS = [
    "Why successful people wake up early",
    "The psychological reason most people never get rich",
    "Why discipline beats motivation every time",
    "The dark secret behind every successful person",
    "Why most people give up right before success",
    "The psychological habit that separates winners from losers",
    "Why rich people think differently than poor people",
    "The one mental trick that changed my life forever",
    "Why average people fear success more than failure",
    "The psychological reason you self sabotage your goals",
    "Why entrepreneurs are more likely to be mentally ill",
    "The dark psychology of hustle culture",
    "Why most people are terrified of their own potential",
    "The psychological reason you fear success",
    "Why mediocrity feels safer than greatness",
    "The one thing every successful person does differently",
    "Why lazy people are actually smarter",
    "The psychological cost of chasing money",
    "Why successful people have fewer friends",
    "The dark side of ambition nobody warns you about",
    "Why most people prefer comfort over growth",
    "The psychological reason you compare yourself to others",
    "Why discipline is more important than talent",
    "The one habit that destroys your potential",
    "Why successful people wake up at 5 AM",
    "The psychological reason you fear failure",
    "Why most people are addicted to their comfort zone",
    "The dark truth about the rat race",
    "Why rich people are lonelier than poor people",
    "The psychological weapon of the wealthy",
]

# ─── EMOTIONS & FEELINGS ─────────────────────────────────────────
EMOTIONS = [
    "Why you feel empty even when your life is good",
    "The psychological reason you feel emotions so deeply",
    "Why some people are naturally happier than others",
    "The dark truth about emotional intelligence",
    "Why you always feel tired even when you sleep enough",
    "The psychological reason you cry for no reason",
    "Why some people are naturally optimistic",
    "The emotion that is more powerful than fear",
    "Why you always feel anxious before good things happen",
    "The psychological reason you feel guilty for being happy",
    "Why some people are emotionally numb",
    "The dark side of being an empath",
    "Why you always feel like something is missing",
    "The psychological reason you feel disconnected from people",
    "Why some people are naturally calm under pressure",
    "The emotion that controls everything you do",
    "Why you always feel like an outsider",
    "The psychological reason you feel overwhelmed by small tasks",
    "Why some people are naturally resilient",
    "The dark truth about people who smile all the time",
    "Why you always feel like you don't belong",
    "The psychological reason you fear happy endings",
    "Why some people are naturally anxious",
    "The emotion that destroys relationships faster than anger",
    "Why you always feel like you're running out of time",
    "The psychological reason you feel emotions in your body",
    "Why some people are naturally pessimistic",
    "The dark side of feeling everything so deeply",
    "Why you always feel like you're pretending to be someone else",
    "The psychological reason you can't let go of the past",
]

# ─── HABITS & BEHAVIOR ───────────────────────────────────────────
HABITS = [
    "The psychology behind why we procrastinate",
    "Why your brain always picks the easy option",
    "The psychological reason you can't break bad habits",
    "Why you always check your phone first thing in the morning",
    "The dark truth about dopamine addiction",
    "Why you always eat when you're not hungry",
    "The psychological reason you can't stop scrolling",
    "Why you always hit the snooze button",
    "The brain hack that rewires your habits instantly",
    "Why you always procrastinate on the most important tasks",
    "The psychological reason you bite your nails",
    "Why you always oversleep on weekends",
    "The dark side of routine nobody talks about",
    "Why you always check your phone during conversations",
    "The psychological reason you can't stick to a diet",
    "Why you always say yes when you mean no",
    "The brain trick that makes you addicted to social media",
    "Why you always buy things you don't need",
    "The psychological reason you always arrive late",
    "Why you can't stop watching videos at 3 AM",
    "The dark truth about your daily routine",
    "Why you always avoid difficult conversations",
    "The psychological reason you can't concentrate for more than 10 minutes",
    "Why you always feel the need to be busy",
    "The brain hack that makes you productive instantly",
    "Why you always feel restless when nothing is wrong",
    "The psychological reason you always interrupt people",
    "Why you can't stop thinking about food",
    "The dark side of perfectionism nobody warns you about",
    "Why you always feel the need to check your notifications",
]

# ─── SOCIAL DYNAMICS ─────────────────────────────────────────────
SOCIAL = [
    "Why popular people are often the loneliest",
    "The psychological reason you feel judged by everyone",
    "Why some people naturally command respect",
    "The social skill that changes everything",
    "Why you always feel awkward in social situations",
    "The psychological reason you can't make friends easily",
    "Why some people are naturally charming",
    "The dark truth about social anxiety",
    "Why you always feel like you don't fit in",
    "The psychological weapon used in every social interaction",
    "Why some people are naturally good leaders",
    "The social dynamic that controls every group",
    "Why you always feel drained after socializing",
    "The psychological reason you fear rejection so much",
    "Why some people are naturally good at networking",
    "The dark side of people pleasing",
    "Why you always feel like you're performing for others",
    "The psychological reason you can't say no",
    "Why some people naturally attract followers",
    "The social skill most people never learn",
    "Why you always feel invisible in a crowd",
    "The psychological reason you fear public speaking",
    "Why some people are naturally good at small talk",
    "The dark truth about introverts in social situations",
    "Why you always feel like you're being watched",
    "The psychological reason you can't be yourself around others",
    "Why some people are naturally good at reading people",
    "The social dynamic that makes people like you instantly",
    "Why you always feel drained after meeting new people",
    "The psychological reason you avoid parties",
]

# ─── MEMORY & LEARNING ───────────────────────────────────────────
MEMORY = [
    "Why your memories are probably fake",
    "The psychological reason you forget things instantly",
    "Why some people have perfect memory",
    "The brain hack that improves your memory instantly",
    "Why you always forget where you put your keys",
    "The psychological reason you can't remember names",
    "Why your brain deletes important memories",
    "The dark truth about false memories",
    "Why you always forget what you were about to say",
    "The psychological reason you can't study effectively",
    "Why some people are naturally good at learning languages",
    "The memory trick that makes you remember everything",
    "Why you always forget your dreams",
    "The psychological reason you can't focus while reading",
    "Why some people have photographic memory",
    "The brain hack that makes you learn anything faster",
    "Why you always mix up similar memories",
    "The psychological reason you can't remember your childhood",
    "Why some people are naturally good at puzzles",
    "The memory palace technique explained simply",
    "Why you always forget people's names instantly",
    "The psychological reason you have brain fog",
    "Why some people are naturally good at math",
    "The dark side of having a great memory",
    "Why you always feel like your brain is running slowly",
    "The psychological reason you can't remember what you read",
    "Why some people are naturally curious about everything",
    "The brain hack that rewires your learning ability",
    "Why you always forget important dates",
    "The psychological reason you can't retain information",
]

# ─── FEAR & ANXIETY ──────────────────────────────────────────────
FEAR = [
    "Why your brain creates fears that don't exist",
    "The psychological reason you're afraid of everything",
    "Why some people are naturally fearless",
    "The dark truth about anxiety nobody tells you",
    "Why you always feel anxious for no reason",
    "The fear that controls more people than you think",
    "Why some people thrive under pressure",
    "The psychological reason you overthink everything",
    "Why your brain can't distinguish real from fake danger",
    "The fear that's holding you back from success",
    "Why some people are naturally calm in chaos",
    "The psychological reason you avoid new experiences",
    "Why your fears always come true",
    "The dark side of being fearless",
    "Why you always feel like something bad is about to happen",
    "The psychological reason you fear success",
    "Why some people are naturally good at handling stress",
    "The fear that makes you procrastinate on everything",
    "Why you always feel paranoid in public places",
    "The psychological reason you can't sleep at night",
    "Why some people are naturally good at managing anxiety",
    "The dark truth about phobias nobody understands",
    "Why you always feel like the world is against you",
    "The psychological reason you fear change so much",
    "Why your anxiety gets worse at night",
    "The fear that's destroying your relationships",
    "Why some people are naturally optimistic about the future",
    "The psychological reason you always expect the worst",
    "Why your brain makes you fear things you love",
    "The dark truth about social anxiety in 2026",
]

# ─── SLEEP & DREAMS ──────────────────────────────────────────────
SLEEP = [
    "Why you always wake up at 3 AM",
    "The psychological reason you can't fall asleep",
    "Why some people need less sleep than others",
    "The dark truth about sleep deprivation",
    "Why your brain is more active at night",
    "The psychological reason you always feel tired",
    "Why you always have the same dream",
    "The brain hack that makes you fall asleep in 2 minutes",
    "Why you always wake up before your alarm",
    "The psychological meaning of your dreams",
    "Why some people are naturally night owls",
    "The dark side of sleeping too much",
    "Why you always dream about falling",
    "The psychological reason you can't nap during the day",
    "Why your brain refuses to shut off at night",
    "The sleep position that reveals your personality",
    "Why you always dream about your ex",
    "The psychological reason you talk in your sleep",
    "Why some people never dream",
    "The dark truth about sleep paralysis",
    "Why you always feel groggy in the morning",
    "The psychological reason you can't sleep without noise",
    "Why you always dream about being chased",
    "The brain hack that improves your sleep quality",
    "Why you always wake up at the same time every night",
    "The psychological meaning of teeth falling out in dreams",
    "Why some people are naturally early birds",
    "The dark side of screen time before bed",
    "Why you always feel tired even after 8 hours of sleep",
    "The psychological reason you dream about flying",
]

# ─── FOOD & EATING ───────────────────────────────────────────────
FOOD = [
    "Why you always eat when you're stressed",
    "The psychological reason you crave junk food",
    "Why some people can eat anything and stay thin",
    "The dark truth about emotional eating",
    "Why you always overeat at night",
    "The psychological reason you're addicted to sugar",
    "Why some people naturally eat slowly",
    "The brain hack that stops cravings instantly",
    "Why you always feel hungry after eating",
    "The psychological reason you can't stick to a diet",
    "Why some people are naturally good cooks",
    "The dark side of food addiction nobody talks about",
    "Why you always eat when you're bored",
    "The psychological reason you comfort eat",
    "Why your brain makes you eat when you're not hungry",
    "The food that secretly destroys your brain",
    "Why you always feel guilty after eating",
    "The psychological reason you can't stop snacking",
    "Why some people are naturally picky eaters",
    "The brain hack that makes you eat less without noticing",
    "Why you always crave what you can't have",
    "The psychological reason you eat faster than everyone else",
    "Why you always feel hungry during dieting",
    "The dark truth about meal planning addiction",
    "Why some people are naturally thin no matter what they eat",
    "The psychological reason you eat your feelings",
    "Why your brain rewards you for eating unhealthy food",
    "The food that secretly makes you depressed",
    "Why you always feel tired after eating",
    "The psychological reason you can't resist dessert",
]

# ─── MONEY & FINANCES ────────────────────────────────────────────
MONEY = [
    "The psychological reason most people stay poor",
    "Why rich people are happier than poor people",
    "The dark truth about money and happiness",
    "Why you always spend money you don't have",
    "The psychological reason you fear being rich",
    "Why some people are naturally good with money",
    "The brain hack that makes you save money automatically",
    "Why you always feel guilty about spending money",
    "The psychological reason you compare your wealth to others",
    "Why money can't buy happiness but poverty guarantees misery",
    "The dark side of financial success nobody warns you about",
    "Why you always buy things to impress people you don't like",
    "The psychological reason you can't save money",
    "Why some people naturally attract wealth",
    "The money mindset that separates rich from poor",
    "Why you always feel anxious about your finances",
    "The psychological reason you avoid checking your bank account",
    "Why some people are naturally frugal",
    "The dark truth about debt and mental health",
    "Why you always feel like you never have enough money",
    "The psychological weapon used in every sales pitch",
    "Why rich people think differently about time",
    "The money habit that makes you wealthier every year",
    "Why you always overspend when you're emotional",
    "The psychological reason you fear asking for a raise",
    "Why some people are naturally good at investing",
    "The dark side of financial independence nobody talks about",
    "Why you always feel like you're falling behind financially",
    "The psychological reason you avoid financial planning",
    "Why money creates more problems than it solves",
]

# ─── HEALTH & BODY ───────────────────────────────────────────────
HEALTH = [
    "Why your body stores fat in specific places",
    "The psychological reason you always feel sick",
    "Why some people never get sick",
    "The dark truth about the placebo effect",
    "Why your brain creates physical pain from emotions",
    "The psychological reason you always feel tired",
    "Why some people heal faster than others",
    "The brain hack that boosts your immune system",
    "Why you always get sick during stressful times",
    "The psychological reason you can't lose weight",
    "Why some people are naturally athletic",
    "The dark side of exercise addiction",
    "Why your body rejects healthy food sometimes",
    "The psychological reason you always feel bloated",
    "Why you always get headaches when you're stressed",
    "The brain body connection nobody understands",
    "Why some people are naturally flexible",
    "The psychological reason you can't stop scratching",
    "Why your body aches when you're sad",
    "The dark truth about chronic fatigue nobody tells you",
    "Why you always feel cold when you're anxious",
    "The psychological reason you always feel hungry",
    "Why some people are naturally strong",
    "The brain hack that reduces inflammation instantly",
    "Why you always feel dizzy when you stand up fast",
    "The psychological reason you can't quit sugar",
    "Why your body reacts to thoughts like they're real",
    "The dark side of health anxiety",
    "Why you always feel better after crying",
    "The psychological reason your posture reflects your mood",
]

# ─── TIME & PROCRASTINATION ──────────────────────────────────────
TIME = [
    "Why time flies when you're having fun",
    "The psychological reason you always run late",
    "Why some people are naturally punctual",
    "The dark truth about time management",
    "Why you always feel like there aren't enough hours in the day",
    "The psychological reason you procrastinate on everything",
    "Why time speeds up as you get older",
    "The brain hack that makes you manage time better",
    "Why you always waste time on your phone",
    "The psychological reason you can't stick to schedules",
    "Why some people are naturally efficient",
    "The dark side of being productive all the time",
    "Why you always feel rushed in the morning",
    "The psychological reason you avoid deadlines",
    "Why your brain refuses to focus on boring tasks",
    "The time management trick that changes everything",
    "Why you always feel like you're running out of time",
    "The psychological reason you can't plan ahead",
    "Why some people are naturally good at multitasking",
    "The dark truth about busy culture",
    "Why you always check the time when you're anxious",
    "The psychological reason you always hit snooze",
    "Why your brain makes you wait until the last minute",
    "The time perception trick that makes days feel longer",
    "Why you always feel behind schedule",
    "The psychological reason you can't say no to requests",
    "Why some people are naturally organized",
    "The dark side of time management systems",
    "Why you always feel like you're wasting your life",
    "The psychological reason you can't enjoy the present moment",
]

# ─── CREATIVITY & IMAGINATION ────────────────────────────────────
CREATIVITY = [
    "Why creative people are often mentally ill",
    "The psychological reason you can't think of ideas",
    "Why some people are naturally creative",
    "The dark truth about writer's block",
    "Why you always have your best ideas in the shower",
    "The brain hack that unlocks your creativity instantly",
    "Why creative people are harder to brainwash",
    "The psychological reason you fear creating anything",
    "Why your brain generates better ideas when you're tired",
    "The dark side of being highly creative",
    "Why you always second guess your creative work",
    "The psychological reason you can't finish projects",
    "Why some people are naturally good at art",
    "The creativity trick used by every genius",
    "Why you always feel inspired at the worst times",
    "The psychological reason you fear sharing your work",
    "Why your brain is more creative when you're relaxed",
    "The dark truth about creative perfectionism",
    "Why you always compare your work to others",
    "The brain hack that makes you more creative overnight",
    "Why creative people are naturally night owls",
    "The psychological reason you can't start new projects",
    "Why some people are naturally good at music",
    "The dark side of creative burnout",
    "Why you always feel like your ideas aren't good enough",
    "The psychological reason you fear rejection of your art",
    "Why your brain generates ideas when you're not trying",
    "The creativity paradox nobody understands",
    "Why you always feel drained after being creative",
    "The psychological reason you procrastinate on creative work",
]

# ─── POWER & DOMINANCE ───────────────────────────────────────────
POWER = [
    "Why powerful people are often the most insecure",
    "The psychological reason you fear authority",
    "Why some people naturally dominate conversations",
    "The dark truth about leadership nobody talks about",
    "Why you always feel intimidated by confident people",
    "The psychological weapon hidden in every power move",
    "Why some people naturally command respect",
    "The brain hack that makes you instantly more confident",
    "Why you always feel small around successful people",
    "The dark side of being in charge",
    "Why powerful people always seem tired",
    "The psychological reason you fear public speaking",
    "Why some people are naturally dominant",
    "The power dynamic that controls every relationship",
    "Why you always feel like you're performing for others",
    "The psychological reason you avoid leadership roles",
    "Why your body language reveals your power level instantly",
    "The dark truth about corporate politics",
    "Why you always feel anxious around authority figures",
    "The power move that changes how people see you",
    "Why some people are naturally good at negotiating",
    "The psychological reason you can't assert yourself",
    "Why powerful people make the worst friends",
    "The dark side of charisma nobody warns you about",
    "Why you always feel like an imposter in charge",
    "The psychological weapon used in every boardroom",
    "Why some people naturally attract followers",
    "The power posture that changes your brain chemistry",
    "Why you always feel powerless in arguments",
    "The dark truth about power corrupts everyone",
]

# ─── HIDDEN TRUTHS ───────────────────────────────────────────────
HIDDEN_TRUTHS = [
    "The psychological reason you feel empty inside",
    "Why your brain is wired to make you unhappy",
    "The dark truth about human nature nobody admits",
    "Why you always feel like something is missing in life",
    "The psychological reason you fear being alone",
    "Why most people live their entire lives without really living",
    "The hidden reason you always feel like an outsider",
    "Why your brain lies to you about everything",
    "The psychological truth about happiness nobody tells you",
    "Why you always feel like you're pretending to be someone else",
    "The dark secret behind every smile you see",
    "Why your brain creates problems that don't exist",
    "The psychological reason you can't be truly honest with anyone",
    "Why most people are secretly miserable",
    "The hidden truth about why we exist",
    "Why you always feel like time is running out",
    "The psychological reason you fear death so much",
    "Why your brain makes you self destructive",
    "The dark truth about human connection",
    "Why you always feel disconnected from everyone",
    "The psychological reason you can't find meaning in life",
    "Why most people are afraid to be themselves",
    "The hidden reason you always feel anxious",
    "Why your brain makes you feel like you're not enough",
    "The dark truth about social media and your brain",
    "Why you always feel like you're missing out on life",
    "The psychological reason you fear growing old",
    "Why your brain makes you compare yourself to everyone",
    "The hidden truth about why we dream",
    "Why you always feel like you're running from something",
]

# ─── MANIPULATION & PERSUASION ───────────────────────────────────
MANIPULATION = [
    "How to make anyone do what you want",
    "The psychological trick that makes people obey you",
    "Why people always say yes to this one request",
    "The dark art of reverse psychology",
    "How to control any conversation without speaking",
    "The psychological weapon that wins every argument",
    "Why people always agree with the most confident person",
    "The manipulation technique used by every politician",
    "How to make someone fall in love with you instantly",
    "The psychological trick that makes you irresistible",
    "Why people always trust someone who disagrees with them",
    "The dark psychology of advertising nobody talks about",
    "How to read someone's mind using body language",
    "The psychological weapon that destroys every relationship",
    "Why people always follow the leader without questioning",
    "The manipulation tactic that works on everyone",
    "How to make anyone confess the truth",
    "The psychological trick that makes people fear you",
    "Why people always give in to this one demand",
    "The dark art of emotional manipulation",
    "How to make someone miss you desperately",
    "The psychological weapon hidden in every conversation",
    "Why people always believe someone who sounds certain",
    "The manipulation technique used by cult leaders",
    "How to make anyone respect you instantly",
    "The psychological trick that makes you unforgettable",
    "Why people always trust someone who disagrees with authority",
    "The dark psychology of social media manipulation",
    "How to control someone without them knowing",
    "The psychological weapon that changes everything",
]

# ─── DECISION MAKING ─────────────────────────────────────────────
DECISIONS = [
    "Why you always make the wrong decision",
    "The psychological reason you can't decide anything",
    "Why some people are naturally decisive",
    "The dark truth about decision fatigue",
    "Why you always regret your decisions",
    "The brain hack that makes you decide faster",
    "Why you always second guess yourself",
    "The psychological reason you avoid making choices",
    "Why your brain makes you choose the wrong option",
    "The decision making trick that changes everything",
    "Why you always feel paralyzed by choice",
    "The psychological reason you always ask others for advice",
    "Why some people are naturally good at making decisions",
    "The dark side of being too logical",
    "Why you always make impulsive decisions when emotional",
    "The psychological weapon that influences every choice",
    "Why you always feel like you made the wrong decision",
    "The decision making bias that ruins your life",
    "Why your brain can't handle too many options",
    "The psychological reason you avoid commitment",
    "Why some people naturally trust their gut",
    "The dark truth about decision making under pressure",
    "Why you always feel anxious after making a decision",
    "The brain hack that removes decision fatigue",
    "Why you always feel like there's a better option",
    "The psychological reason you procrastinate on decisions",
    "Why your brain makes you choose familiarity over quality",
    "The decision making trap that controls your life",
    "Why you always feel unsure about your choices",
    "The psychological reason you fear making mistakes",
]

# ─── IDENTITY & SELF ─────────────────────────────────────────────
IDENTITY = [
    "Why you don't really know who you are",
    "The psychological reason you wear masks around people",
    "Why some people have a strong sense of self",
    "The dark truth about identity in modern society",
    "Why you always feel like you're playing a role",
    "The psychological reason you fear being truly known",
    "Why your personality changes depending on who you're with",
    "The brain hack that helps you find your true self",
    "Why you always feel like you're pretending",
    "The dark side of people pleasing nobody talks about",
    "Why you always feel like you don't belong anywhere",
    "The psychological reason you can't be honest with yourself",
    "Why some people naturally know who they are",
    "The identity crisis nobody warns you about",
    "Why you always feel like you're losing yourself",
    "The psychological weapon that controls your identity",
    "Why your mirror image isn't how others see you",
    "The dark truth about self image in 2026",
    "Why you always feel like you're two different people",
    "The psychological reason you change your personality online",
    "Why some people are naturally authentic",
    "The identity paradox that drives you crazy",
    "Why you always feel like you're not living your real life",
    "The psychological reason you fear growing up",
    "Why your brain creates a false version of yourself",
    "The dark side of identity politics",
    "Why you always feel like you're running from yourself",
    "The psychological reason you can't accept who you are",
    "Why some people naturally embrace their flaws",
    "The identity hack that changes everything",
]

# ─── DEATH & MORTALITY ───────────────────────────────────────────
DEATH = [
    "Why you always think about death at night",
    "The psychological reason you fear dying",
    "Why some people are naturally calm about death",
    "The dark truth about mortality nobody admits",
    "Why your brain makes you obsessed with death",
    "The psychological weapon that makes you fear everything",
    "Why you always feel like time is running out",
    "The brain hack that makes you accept mortality",
    "Why you always feel anxious about getting older",
    "The dark side of death anxiety nobody talks about",
    "Why you always think about what happens after death",
    "The psychological reason you fear losing loved ones",
    "Why some people are naturally philosophical about death",
    "The mortality paradox that drives you crazy",
    "Why you always feel like you're wasting your life",
    "The psychological weapon that makes you fear the future",
    "Why your brain reminds you of death at random moments",
    "The dark truth about funeral anxiety",
    "Why you always feel like you're not prepared to die",
    "The psychological reason you avoid thinking about death",
    "Why some people naturally accept their mortality",
    "The death anxiety that controls your decisions",
    "Why you always feel like you're running out of time",
    "The psychological reason you fear being forgotten",
    "Why your brain makes you think about death before sleep",
    "The dark side of death awareness",
    "Why you always feel like life is too short",
    "The psychological reason you fear the unknown",
    "Why some people naturally make peace with death",
    "The mortality hack that changes your perspective",
]

# ─── ALL CATEGORIES COMBINED ─────────────────────────────────────
ALL_CATEGORIES = {
    "dark_psychology": DARK_PSYCHOLOGY,
    "intelligence": INTELLIGENCE,
    "body_language": BODY_LANGUAGE,
    "relationships": RELATIONSHIPS,
    "cognitive_biases": COGNITIVE_BIASES,
    "success": SUCCESS,
    "emotions": EMOTIONS,
    "habits": HABITS,
    "social": SOCIAL,
    "memory": MEMORY,
    "fear": FEAR,
    "sleep": SLEEP,
    "food": FOOD,
    "money": MONEY,
    "health": HEALTH,
    "time": TIME,
    "creativity": CREATIVITY,
    "power": POWER,
    "hidden_truths": HIDDEN_TRUTHS,
    "manipulation": MANIPULATION,
    "decisions": DECISIONS,
    "identity": IDENTITY,
    "death": DEATH,
}

# ─── FLAT LIST OF ALL TOPICS ─────────────────────────────────────
ALL_TOPICS = []
for category_topics in ALL_CATEGORIES.values():
    ALL_TOPICS.extend(category_topics)

# Remove duplicates while preserving order
seen = set()
UNIQUE_TOPICS = []
for topic in ALL_TOPICS:
    if topic not in seen:
        seen.add(topic)
        UNIQUE_TOPICS.append(topic)

# ─── STATS ───────────────────────────────────────────────────────
def get_stats():
    """Return statistics about the topics database."""
    stats = {
        "total_topics": len(UNIQUE_TOPICS),
        "categories": len(ALL_CATEGORIES),
        "topics_per_category": {k: len(v) for k, v in ALL_CATEGORIES.items()},
    }
    return stats

if __name__ == "__main__":
    stats = get_stats()
    print(f"Total topics: {stats['total_topics']}")
    print(f"Categories: {stats['categories']}")
    for cat, count in stats['topics_per_category'].items():
        print(f"  {cat}: {count} topics")
